In [ ]:
import pandas as pd
low_memory=False #pq o arquivo é muito grande e memo assim meu pc ainda n abre as vezes hahaha
%matplotlib notebook

In [15]:

seila = pd.read_csv(r'C:\Users\andrey\Documents\GitHub\Cure-analysis-Covid-19-Brazil\HIST_PAINEL_COVIDBR_03jul2020.csv', delimiter=';')
#o utf-8 é melhos nesse caso pois a codificaçã

In [16]:
for k in range(17): print (k, seila.columns[k]) #pega todas as colunas do doido

0 regiao
1 estado
2 municipio
3 coduf
4 codmun
5 codRegiaoSaude
6 nomeRegiaoSaude
7 data
8 semanaEpi
9 populacaoTCU2019
10 casosAcumulado
11 casosNovos
12 obitosAcumulado
13 obitosNovos
14 Recuperadosnovos
15 emAcompanhamentoNovos
16 interior/metropolitana

In [17]:
seila

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,data,semanaEpi,populacaoTCU2019,casosAcumulado,casosNovos,obitosAcumulado,obitosNovos,Recuperadosnovos,emAcompanhamentoNovos,interior/metropolitana
0,Brasil,NaN,NaN,76,NaN,NaN,NaN,25/02/2020,9,210147125,0,0,0,0,NaN,NaN,NaN
1,Brasil,NaN,NaN,76,NaN,NaN,NaN,26/02/2020,9,210147125,1,1,0,0,NaN,NaN,NaN
2,Brasil,NaN,NaN,76,NaN,NaN,NaN,27/02/2020,9,210147125,1,0,0,0,NaN,NaN,NaN
3,Brasil,NaN,NaN,76,NaN,NaN,NaN,28/02/2020,9,210147125,1,0,0,0,NaN,NaN,NaN
4,Brasil,NaN,NaN,76,NaN,NaN,NaN,29/02/2020,9,210147125,2,1,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535859,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,29/06/2020,27,3015268,47071,2166,559,11,NaN,NaN,1.0
535860,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,30/06/2020,27,3015268,49218,2147,587,28,NaN,NaN,1.0
535861,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,01/07/2020,27,3015268,50676,1458,620,33,NaN,NaN,1.0
535862,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,02/07/2020,27,3015268,52281,1605,631,11,NaN,NaN,1.0
535863,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,03/07/2020,27,3015268,53996,1715,643,12,NaN,NaN,1.0

In [20]:
seila.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 535864 entries, 0 to 535863
Data columns (total 17 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   regiao                  535864 non-null  object
 1   estado                  535734 non-null  object
 2   municipio               530145 non-null  object
 3   coduf                   535864 non-null  int64
 4   codmun                  532224 non-null  float64
 5   codRegiaoSaude          530145 non-null  float64
 6   nomeRegiaoSaude         530145 non-null  object
 7   data                    535864 non-null  object
 8   semanaEpi               535864 non-null  int64
 9   populacaoTCU2019        533785 non-null  object
 10  casosAcumulado          535864 non-null  int64
 11  casosNovos              535864 non-null  int64
 12  obitosAcumulado         535864 non-null  int64
 13  obitosNovos             535864 non-null  int64
 14  Recuperadosnovos        76 non-null      float64
 15  emAcompanhamentoNovos   76 non-null      float64
 16  interior/metropolitana  530145 non-null  float64
dtypes: float64(5), int64(6), object(6)
memory usage: 69.5+ MB

In [21]:
seila.shape

(535864, 17)

In [22]:
seila.describe()

,coduf,codmun,codRegiaoSaude,semanaEpi,casosAcumulado,casosNovos,obitosAcumulado,obitosNovos,Recuperadosnovos,emAcompanhamentoNovos,interior/metropolitana
count,535864.000000,532224.000000,530145.000000,535864.000000,5.358640e+05,535864.000000,535864.000000,535864.000000,76.000000,76.000000,530145.000000
mean,32.080246,322476.410528,32123.513725,20.267792,2.331577e+02,8.616446,11.835768,0.353676,261022.868421,254448.802632,0.071709
std,9.780099,97484.738466,9729.462448,4.106503,8.796845e+03,297.752383,430.462416,11.338205,248886.836752,189441.451316,0.258005
min,11.000000,110000.000000,11001.000000,9.000000,0.000000e+00,-1812.000000,0.000000,-36.000000,22130.000000,14062.000000,0.000000
25%,25.000000,250977.500000,25008.000000,17.000000,0.000000e+00,0.000000,0.000000,0.000000,58310.250000,74753.000000,0.000000
50%,31.000000,314125.000000,31051.000000,20.000000,1.000000e+00,0.000000,0.000000,0.000000,162620.000000,213846.500000,0.000000
75%,41.000000,411282.500000,41011.000000,24.000000,1.200000e+01,0.000000,0.000000,0.000000,394432.000000,432995.000000,0.000000
max,76.000000,530010.000000,53001.000000,27.000000,1.539081e+06,54771.000000,63174.000000,1473.000000,868372.000000,607535.000000,1.000000

In [23]:
seila.info

<bound method DataFrame.info of               regiao estado municipio  coduf    codmun  codRegiaoSaude  \
0             Brasil    NaN       NaN     76       NaN             NaN
1             Brasil    NaN       NaN     76       NaN             NaN
2             Brasil    NaN       NaN     76       NaN             NaN
3             Brasil    NaN       NaN     76       NaN             NaN
4             Brasil    NaN       NaN     76       NaN             NaN
...              ...    ...       ...    ...       ...             ...
535859  Centro-Oeste     DF  Brasília     53  530010.0         53001.0
535860  Centro-Oeste     DF  Brasília     53  530010.0         53001.0
535861  Centro-Oeste     DF  Brasília     53  530010.0         53001.0
535862  Centro-Oeste     DF  Brasília     53  530010.0         53001.0
535863  Centro-Oeste     DF  Brasília     53  530010.0         53001.0

         nomeRegiaoSaude        data  semanaEpi populacaoTCU2019  \
0                    NaN  25/02/2020          9        210147125
1                    NaN  26/02/2020          9        210147125
2                    NaN  27/02/2020          9        210147125
3                    NaN  28/02/2020          9        210147125
4                    NaN  29/02/2020          9        210147125
...                  ...         ...        ...              ...
535859  DISTRITO FEDERAL  29/06/2020         27          3015268
535860  DISTRITO FEDERAL  30/06/2020         27          3015268
535861  DISTRITO FEDERAL  01/07/2020         27          3015268
535862  DISTRITO FEDERAL  02/07/2020         27          3015268
535863  DISTRITO FEDERAL  03/07/2020         27          3015268

        casosAcumulado  casosNovos  obitosAcumulado  obitosNovos  \
0                    0           0                0            0
1                    1           1                0            0
2                    1           0                0            0
3                    1           0                0            0
4                    2           1                0            0
...                ...         ...              ...          ...
535859           47071        2166              559           11
535860           49218        2147              587           28
535861           50676        1458              620           33
535862           52281        1605              631           11
535863           53996        1715              643           12

        Recuperadosnovos  emAcompanhamentoNovos  interior/metropolitana
0                    NaN                    NaN                     NaN
1                    NaN                    NaN                     NaN
2                    NaN                    NaN                     NaN
3                    NaN                    NaN                     NaN
4                    NaN                    NaN                     NaN
...                  ...                    ...                     ...
535859               NaN                    NaN                     1.0
535860               NaN                    NaN                     1.0
535861               NaN                    NaN                     1.0
535862               NaN                    NaN                     1.0
535863               NaN                    NaN                     1.0

[535864 rows x 17 columns]>

In [26]:
seila.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 535864 entries, 0 to 535863
Data columns (total 17 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   regiao                  535864 non-null  object
 1   estado                  535734 non-null  object
 2   municipio               530145 non-null  object
 3   coduf                   535864 non-null  int64
 4   codmun                  532224 non-null  float64
 5   codRegiaoSaude          530145 non-null  float64
 6   nomeRegiaoSaude         530145 non-null  object
 7   data                    535864 non-null  object
 8   semanaEpi               535864 non-null  int64
 9   populacaoTCU2019        533785 non-null  object
 10  casosAcumulado          535864 non-null  int64
 11  casosNovos              535864 non-null  int64
 12  obitosAcumulado         535864 non-null  int64
 13  obitosNovos             535864 non-null  int64
 14  Recuperadosnovos        76 non-null      float64
 15  emAcompanhamentoNovos   76 non-null      float64
 16  interior/metropolitana  530145 non-null  float64
dtypes: float64(5), int64(6), object(6)
memory usage: 69.5+ MB

In [25]:
seila.groupby('casosAcumulado').size().sort_values().tail(3).plot(kind='barh')

In [12]:
seila.query('casosAcumulado')['data'].value_counts().tail(3).plot(kind='barh')

KeyError: 'Passing list-likes to .loc or [] with any missing labels is no longer supported, see https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike'

In [ ]:
seila.groupby('data').size().sort_values().tail(3).plot(kind='barh')

In [ ]:
dates = pd.date_range('25/02/2020', periods=129)

In [ ]:
df = pd.DataFrame(index=dates, columns=['casosAcumulado', 'casosNovos', 'obitosAcumulado', 'obitosNovos'])

In [ ]:
seila.query('regiao == "Brasil" ')['casosNovos'].tail(5).plot(kind='barh')

In [ ]:
seila.query('regiao == "Brasil" ')['Recuperadosnovos'].tail(5).plot(kind='barh')